### PR TITLE
Update to latest master, hunterize

### PR DESCRIPTION
**Pull request by rbsheth**
@ruslo

### CODE REVIEW

**Review by ruslo — CHANGES_REQUESTED** [review]
> cleanup and rename

> downgrade HunterGate 

Please refactor it into "Add HunterGate module", "HunterGate with URL/SHA1", "Hunterize". See:
- https://docs.hunter.sh/en/latest/creating-new/patch.html

**Comment by rbsheth** [comment]
@ruslo fixed, PTAL

**Comment by rbsheth** [comment]
Also, I believe the base branch should be named `hunter-packages:hunter-2.0.0-e33f534` since v2.0.0 has officially been released: https://github.com/libigl/libigl/releases/tag/v2.0.0

**Comment by ruslo** [comment]
>  I believe the base branch should be named hunter-packages:hunter-2.0.0-e33f534 since v2.0.0 has officially been released

That is really confusing but commit for `v1.3.3` is the same as for `v2.0.0`:
- https://github.com/libigl/libigl/releases/tag/v1.3.3
- https://github.com/libigl/libigl/releases/tag/v2.0.0

```
> git describe --tags  v2.0.0
v1.3.3

> git describe --tags  v1.3.3
v1.3.3

> git rev-list -n 1 v1.3.3
ed363da1f624e7a2f802f6b04973be8ea63f0511

> git rev-list -n 1 v2.0.0
ed363da1f624e7a2f802f6b04973be8ea63f0511
```

**Review by ruslo — APPROVED** [review]

**Comment by ruslo** [comment]
Released: https://github.com/hunter-packages/libigl/releases/tag/v1.3.3-e33f534-p0

**Comment by rbsheth** [comment]
I think they rewrote the history of their repo - that's probably why the tags are at the same hash. I'm proceeding with `2.0.0` as a version, since it will be less confusing.

**Pull request merged**
